# Generated by Django 3.1.7 on 2021-05-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('hk_grid', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cases',
            fields=[
                ('case_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('person_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('symptoms_date', models.DateField()),
                ('confirmation_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Location_data',
        ),
        migrations.AddField(
            model_name='attendances',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CovidDataPortal.cases'),
        ),
    ]
