# Generated by Django 3.1.7 on 2021-05-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0003_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cases',
            name='id_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cases',
            name='person_name',
            field=models.CharField(max_length=255),
        ),
    ]
