# Generated by Django 3.1.7 on 2021-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0004_auto_20210508_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField()),
                ('person_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('symptoms_date', models.DateField()),
                ('confirmation_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='case',
        ),
        migrations.DeleteModel(
            name='cases',
        ),
    ]
