# Generated by Django 3.1.7 on 2021-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0006_auto_20210508_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField()),
                ('person_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('symptoms_date', models.CharField(max_length=255)),
                ('confirmation_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='case_record',
        ),
    ]
