# Generated by Django 3.1.7 on 2021-05-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0008_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='staffnum',
            field=models.IntegerField(null=True),
        ),
    ]
