# Generated by Django 3.1.7 on 2021-05-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0009_auto_20210509_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='staffnum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
