# Generated by Django 3.1.7 on 2021-05-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0012_auto_20210509_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='case_number_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='event_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='hk_grid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='venue_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='venue_name',
            field=models.CharField(max_length=255),
        ),
    ]
