# Generated by Django 3.1.8 on 2021-05-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0013_auto_20210509_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
