# Generated by Django 3.1.8 on 2021-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0014_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_records',
            name='id',
        ),
        migrations.AlterField(
            model_name='case_records',
            name='case_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
