# Generated by Django 3.1.8 on 2021-05-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidDataPortal', '0015_auto_20210510_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_records',
            name='id_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
